name: json_rpc_adapter
description: HTTP client and shelf server adapters for easier JSON-RPC (optional mirrors for automatic binding).
version: 0.6.0
repository: https://github.com/agilord/json_rpc_adapter

environment:
  sdk: '^3.0.0'

dependencies:
  http: ^1.0.0
  json_rpc_2: ^3.0.0
  shelf: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.0.0
