name: json_rpc_adapter
description: HTTP client and shelf server adapters for easier JSON-RPC, with efficient binary encodings (optional mirrors for automatic binding).
version: 0.7.0
repository: https://github.com/agilord/json_rpc_adapter
topics:
  - json-rpc
  - rpc

environment:
  sdk: '^3.8.0'

dependencies:
  http: ^1.0.0
  json_rpc_2: ^4.0.0
  shelf: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.0.0
